name: ba
channels:
  - defaults
dependencies:
  - python=3.11
  - plotly
  - psycopg2
  - jupyterlab
  - ipykernel
  - pandas
  - openpyxl
  - sqlalchemy
  - numpy
  - pyarrow
  - matplotlib
  - python-dotenv
prefix: C:\Users\HomePC\anaconda3\envs\ba
